version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - xpack.security.authc.anonymous.username=anonymous
      - xpack.security.authc.anonymous.roles=superuser
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=password
      - xpack.security.http.ssl.enabled=false
    ports:
      - '9200:9200'
    networks:
      - bha
    expose:
      - '9200'

  app:
    image: ghcr.io/banned-historical-archives/banned-historical-archives.github.io:latest
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
    networks:
      - bha
    environment:
      - NODE_ENV=development
      - ES_URL=http://elasticsearch:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=password
      # - node_options="--max-old-space-size=8192"
networks:
  bha:
    driver: bridge
