version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
    networks:
      - bha
    environment:
      - NODE_ENV=development
      - node_options="--max-old-space-size=8192" 
      - ES_URL=http://bha:9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - xpack.security.authc.anonymous.username=anonymous_user
      - xpack.security.authc.anonnymous.authz_exceptioin=true
      - xpack.security.authc.anonymous.roles=superuser
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=password
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    networks:
      - bha
    expose:
      - "9200"

networks:
  bha:
    driver: bridge
