name: build
on: [push]

jobs:
  container-job:
    runs-on: node:latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root_password
        ports:
        - 3306:3306
        # needed because the mysql container does not provide a healthcheck
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:
    - uses: actions/checkout@v2
      env:
        # use mysql for the host here because we have specified a container for the job.
        # If we were running the job on the VM this would be localhost
        MYSQL_HOST: mysql
        MYSQL_PORT: 3306
    - run: apt-get update -y -qq
    - run: apt-get install -y -qq --no-install-recommends default-mysql-client
    - run: mysql --user=root --password="root_password" --host=mysql --execute "CREATE DATABASE banned_history CHARACTER SET utf8 COLLATE utf8_general_ci;"
    - run: GITLAB_CI=true npm run init-db
    - run: GITLAB_CI=true npm run build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist

