name: build
on:
  workflow_dispatch:
  push:
    branches: ['master']

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

jobs:
  container-job:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Use Node.js
        uses: actions/setup-node@v3
      - run: npm install
      - run: cp -r ./node_modules/pdfjs-dist ./public/
      - run: node_options="--max-old-space-size=8192" npm run build-catelog
      - run: node_options="--max-old-space-size=8192" npm run dev:nextjs-helper && npm run build
      - run: git config --global http.postBuffer 2097152000
      - run: git config --global user.email "you@example.com"
      - run: git config --global user.name "Your Name"
      - run: git checkout --orphan x
      - run: git reset --hard
      - run: mv out/* ./
      - run: touch .nojekyll
      - run: rm -rf node_modules && rm -rf .next
      - run: git add .
      - run: git commit -m update
      - run: git push origin x:gh-pages -f
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
