name: ocr
on:
  issues:
    types: [opened]

jobs:
  ocr:
    name: OCR
    if: ${{ startsWith(github.event.issue.title, '[自动化文稿录入]') }}
    runs-on: ubuntu-latest
    container:
      image: breezedeus/cnocr:v2.2
      options: --user root
    steps:
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYY-MM-DD-HH-mm-ss'
      - name: Set UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
        with:
          name: prefix${{ env.GITHUB_ACTION }}${{ env.GITHUB_RUN_NUMBER }}${{ github.sha }}${{ steps.time.outputs.time }}
      - run: add-apt-repository -y ppa:git-core/ppa
      - run: apt update
      - run: apt install git -y
      - run: pip install pymupdf
      - run: useradd -u 1001 ci
      - uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.GH_PAT}}
          submodules: true
      - run: git config --global --add safe.directory /__w/banned-historical-archives.github.io/banned-historical-archives.github.io/public/archives0
      - run: git config --global --add safe.directory /__w/banned-historical-archives.github.io/banned-historical-archives.github.io/public/archives1
      - run: git config --global --add safe.directory /__w/banned-historical-archives.github.io/banned-historical-archives.github.io/public/archives2
      - run: git config --global --add safe.directory /__w/banned-historical-archives.github.io/banned-historical-archives.github.io/public/archives3
      - run: git config --global --add safe.directory /__w/banned-historical-archives.github.io/banned-historical-archives.github.io/public/archives4
      - run: git config --global --add safe.directory /__w/banned-historical-archives.github.io/banned-historical-archives.github.io/public/archives5
      - run: git config --global --add safe.directory /__w/banned-historical-archives.github.io/banned-historical-archives.github.io
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
      - run: npm i
      - run: chown -R ci:ci ./
      - id: get_archive_id
        run: echo ::set-output name=archive_id::$(npx ts-node --project ./tsconfig.build.json backend/ocr-gitworkflow-get-archive-id.ts)
        env:
          BODY: ${{ github.event.issue.body }}
          TITLE: ${{ github.event.issue.title }}
      - id: action_with_json_output
        run: echo ::set-output name=data::$(npx ts-node --project ./tsconfig.build.json backend/ocr-gitworkflow.ts)
        env:
          BODY: ${{ github.event.issue.body }}
          TITLE: ${{ github.event.issue.title }}
      - name: Create Pull Request For Submodule
        env:
          GH_TOKEN: ${{ secrets.GH_PAT}}
        run: |
          cd public/archives${{ steps.get_archive_id.outputs.archive_id }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b feat-${{ steps.generate-uuid.outputs.uuid }}
          git add .
          git commit -m 'feat: ${{ github.event.issue.title }}'
          git push origin feat-${{ steps.generate-uuid.outputs.uuid }}
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GH_TOKEN" \
          https://api.github.com/repos/banned-historical-archives/banned-historical-archives${{ steps.get_archive_id.outputs.archive_id }}/pulls \
          -d '{"title":"${{ github.event.issue.title }}","body":"https://github.com/banned-historical-archives/banned-historical-archives.github.io/issues/${{github.event.issue.number}}","head":"feat-${{ steps.generate-uuid.outputs.uuid }}","base":"main"}'
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          body: 'fix #${{ github.event.issue.number }}'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch-suffix: random
          delete-branch: true
          title: '${{ github.event.issue.title }}'
          labels: |
            report
            automated pr
          team-reviewers: |
            owners
            maintainers
          draft: false
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{github.event.issue.number}}
          body: ${{ steps.action_with_json_output.outputs.data }}