name: ocr
on:
  issues:
    types: [opened]

jobs:
  issue:
    name: Issue
    runs-on: ubuntu-latest
    container:
      image: breezedeus/cnocr:v2.2
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - run: |
          git submodule update public/books/archives1
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
      - run: npm i
      - run: npx ts-node --project ./tsconfig.build.json backend/ocr-gitworkflow.ts >> $GITHUB_ENV
        env:
          BODY: ${{ github.event.issue.body }}
          TITLE: ${{ github.event.issue.title }}
      - run: |
          cd public/books/archives1
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "feat: ${{ github.event.issue.title }}"
          git push
      - run: |
          git add .
          git commit -m "feat: ${{ github.event.issue.title }}"
          git push
