name: ocr
on:
  issues:
    types: [opened]

jobs:
  ocr:
    name: OCR
    if: ${{ startsWith(github.event.issue.title, '{自动化文稿录入}') }}
    runs-on: ubuntu-latest
    container:
      image: breezedeus/cnocr:v2.2
      options: --user root
    steps:
      - run: add-apt-repository -y ppa:git-core/ppa
      - run: apt update
      - run: apt install git -y
      - run: useradd -u 1001 ci
      - uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.GH_PAT }}
          submodules: true
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
      - run: npm i
      - run: chown -R ci:ci ./
      - run: npx ts-node --project ./tsconfig.build.json backend/ocr-gitworkflow.ts
        env:
          BODY: ${{ github.event.issue.body }}
          TITLE: ${{ github.event.issue.title }}
      - run: ls -la public/books/archives1/.git
      - run: su ci && mkdir -p public/books/archives1/.git/shallow
      - run: git config --global --add safe.directory /__w/banned-historical-archives.github.io/banned-historical-archives.github.io/public/books/archives1
      - run: cd public/books/archives1 && git status
      - name: Create Pull Request For Submodule
        id: cprs
        uses: peter-evans/create-pull-request@v4
        with:
          body: 'fix #${{ github.event.issue.number }}'
          path: public/books/archives1
          base: 'main'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch-suffix: random
          delete-branch: true
          title: '${{ github.event.issue.title }}'
          labels: |
            report
            automated pr
          team-reviewers: |
            owners
            maintainers
          draft: false
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          body: 'fix #${{ github.event.issue.number }}'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch-suffix: random
          delete-branch: true
          title: '${{ github.event.issue.title }}'
          labels: |
            report
            automated pr
          team-reviewers: |
            owners
            maintainers
          draft: false

