name: patch
on:
  issues:
    types: [opened]

jobs:
  issue:
    name: Issue
    if: ${{ startsWith(github.event.issue.title, '[OCR patch]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
      - run: node patch/index.js
        env:
          COMMIT_HASH: ${{ github.sha }}
          BODY: ${{ github.event.issue.body }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          body: 'fix #${{ github.event.issue.number }}'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch-suffix: random
          delete-branch: true
          title: '[BOT]${{ github.event.issue.title }}'
          labels: |
            report
            automated pr
          draft: false
