name: build
on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

jobs:
  container-job:
    runs-on: ubuntu-22.04
    steps:
      - name: Invoke workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build_parsed_article.yml
          ref: ocr_cache
          repo: banned-historical-archives/banned-historical-archives0
